### ISSUE TITLE
Image read may block on Windows 10

### ISSUE THREAD

**Issue by seth-shi** [golang-design/clipboard#14]
when copy text can get text content;
but copy image, `Read` blocking

```
package main

import (
	"fmt"
	"golang.design/x/clipboard"
)

func main()  {

	fmt.Println(clipboard.Read(clipboard.FmtImage))
}
```

**Comment by changkun** [comment]
？

**Comment by seth-shi** [comment]
module lol

go 1.16

require (
	github.com/kbinani/screenshot v0.0.0-20210720154843-7d3a670d8329 // indirect
	golang.design/x/clipboard v0.5.3
)

**Comment by seth-shi** [comment]
![image](https://user-images.githubusercontent.com/28035971/137135805-a3ce2f06-fe0d-4a5b-8737-bb3922fa279c.png)

no content return empty slice is ok.
but has picture content block

**Comment by seth-shi** [comment]
is not qq problem, is ok on other pc

**Comment by changkun** [comment]
Thanks for the video, can you also provide your system and your Go version?

**Comment by changkun** [comment]
Looks like a user error. Nothing needs to fix here.
