### ISSUE TITLE
gif copy support

### ISSUE THREAD

**Issue by jilieryuyi** [golang-design/clipboard#2]
Can GIF copy be supported?

**Comment by changkun** [comment]
Thanks for the issue!

It is indeed a missing feature, I will do some research and add gif support soon.

**Comment by changkun** [comment]
After a quick research on Linux, it seems that copy gif to the clipboard is rarely possible.

The X11 clipboard works differently than other platforms. It requires other applications to deal with the gif image, and unfortunately, even Chrome does not handle gif images. For instance, if you copy a gif image directly from a webpage, then chrome will convert it to a single static png frame and all other frames are lost.

If you put a gif XAtom target to the clipboard, it also requires others to implement the mechanism where applications support such type of data, and unfortunately, even Chrome does not request the person who own clipboard selection with GIF mime format content in a `XSelectionRequestEvent`.

To conclude, I think gif copy support is barely possible to get well-supported across multiple platforms.
Maybe a better approach is to offer the ability to use and register their own types as a package.

**Comment by changkun** [comment]
Close as explained in above.
