### ISSUE TITLE
Can add some function let us know the bytes is image or text

### ISSUE THREAD

**Issue by 52funny** [golang-design/clipboard#24]
Hi, @changkun Thank you to create the wonderful framework.
Can you provide a way for us to read the clipboard content as a stream of characters or images？

Like this
```go
func IsText() bool
func IsImage() bool
```

**Comment by changkun** [comment]
Hi I don't think you need additional APIs to check if the data is text or image, if you try

```
clipboard.Read(clipboard.FmtText)
```

But the actual content in clipboard is image, the call returns you a nil, same applied to image.

Regarding reading as a stream of characters, I don't know enough about the purpose of it. 
If you just need convert `[]byte` to `io.Reader`, you could try `bytes.NewReader`. Can you elaborate more?

**Comment by changkun** [comment]
Lack of information. Close.
