### ISSUE TITLE
PNG data overwritten on Windows

### ISSUE THREAD

**Issue by abejfehr** [golang-design/clipboard#36]
I'd like to be able to hit "Print Screen" on my keyboard and paste the images into a Steam chat, but as it stands that doesn't work because the screenshots created by Windows are too big in terms of filesize.

I wrote a simple program using this library that uses pngquant to optimize the image data in the clipboard and then replace the clipboard with it, but it doesn't work.

Here's the important code: 

```
imageChannel := clipboard.Watch(context.Background(), clipboard.FmtImage)

copiedImage := <-imageChannel
fmt.Println("detected that an image was copied, compressing image...")

compressedImage, err := pngquant.CompressBytes(copiedImage, "1")

fmt.Println("original image size in bytes:", len(copiedImage))
fmt.Println("compressed image size in bytes:", len(compressedImage))

if err != nil {
	panic(err)
}

fmt.Println("reading clipboard...")
fmt.Println(len(clipboard.Read(clipboard.FmtImage)))

fmt.Println("replacing clipboard...")
clipboard.Write(clipboard.FmtImage, compressedImage)

fmt.Println("reading clipboard...")
fmt.Println(len(clipboard.Read(clipboard.FmtImage)))

```

and here's the output I see:

```
detected that an image was copied, compressing image...
original image size in bytes: 1947271
compressed image size in bytes: 1696311
reading clipboard...
1947271
replacing clipboard...
reading clipboard...
3881712
```

As you can see, the compression _does_ work, but when I write that to the clipboard it's replaced with something much larger, often around 2x the original size(!)

It'd be great if the original bytes could be written to the clipboard without being re-encoded (on Windows)

**Comment by changkun** [comment]
Is pngquant compressed data still in PNG format? The clipboard.Write and clipboard.Read both assumes the data need to be PNG encoded.

**Comment by abejfehr** [comment]
I think so, I added this line:

```
fmt.Println("header data:", compressedImage[0:8])
```

and the output was:

```
header data: [137 80 78 71 13 10 26 10]
```

which seems to imply it's png data, according to this site: http://www.libpng.org/pub/png/spec/1.2/PNG-Structure.html

**Comment by changkun** [comment]
> It'd be great if the original bytes could be written to the clipboard without being re-encoded (on Windows)

I am not sure if this is possible. Windows works differently than macOS, and it requires input bytes must be PNG. This package does not do anything further but just put the bytes into OS required region and let OS do stuff.

**Comment by abejfehr** [comment]
> ...it requires input bytes must be PNG.

I can very much assure you that the input bytes are in PNG, that's not the issue.

It actually looks like Windows does _not_ expect a PNG by the way, so it turns out that's not a requirement for Windows and must just be an arbitrary choice for this library.

The format that this library uses to store the image in the clipboard is called `DIB V5` according to the code [here](https://github.com/golang-design/clipboard/blob/main/clipboard_windows.go#L302), which is described by Microsoft [here](https://learn.microsoft.com/en-us/previous-versions/aa917106(v=msdn.10)?redirectedfrom=MSDN).

Which, it turns out, is a _bitmap_, so it's never going to be my compressed PNG data.

![image](https://user-images.githubusercontent.com/3917428/212549116-9b3c6b81-6a1c-48fa-b480-f88b1261b50b.png)

^ I also used [Free Clipboard Viewer ](https://freeclipboardviewer.com/)to confirm that hitting "Print Screen" does store the data in Bitmap, so this is reasonable.

I think I'm going to have to make my screenshots pasteable by resizing them instead of compressing them because this format isn't compressable.

I'm gonna mark this one as closed, since it's not an issue with the library.
