### ISSUE TITLE
Release v0.4.5 not yet pushed to https://pkg.go.dev/golang.design/x/clipboard

### ISSUE THREAD

**Issue by mc51** [golang-design/clipboard#5]
Thanks for this very helpful package. I noticed a bug in Windows using your package. It seems that you've already fixed it here: #3 
While the new release is pushed on github it is not yet available for "go get" because https://pkg.go.dev/golang.design/x/clipboard still references to v0.4.4 as "LATEST". I'd appreciate, if you could fix this.

**Comment by changkun** [comment]
Hi, thanks for reporting this issue.

This is really strange as the v0.4.5 cannot be updated to the proxy.golang.org. As an alternative solution, I have published a duplicated version 0.4.6 of 0.4.5, which you could fetch this package via:

```
go get golang.design/x/clipboard@v0.4.6 
```

Let me know if this works for you.

**Comment by mc51** [comment]
HI @changkun, thanks for the quick fix. I can confirm that v0.4.6 is now downloaded as latest version. Also, now the clipboard does work for Windows as well (I've only tried text c&p for now).

**Comment by changkun** [comment]
Thanks again for reporting and testing the new version :)
