### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by x777** [golang-design/clipboard#8]
I've tested for Linux and it works perfectly. But for Android not working at all. Not tested with iOS. Any plans for supporting those?

**Comment by changkun** [comment]
Yes, it will be supported in the next versions.

**Comment by changkun** [comment]
After two days of investigation, I don't think it is possible to support Android individually. 

Android requires running an application on JVM where it is initialized at bootstrapping time. Unfortunately, every GUI framework supports its own system of the building (packaging) into a mobile application, such as:

- [gomobile](https://github.com/golang/mobile)
- [fyne](https://fyne.io)
- [gioui](https://gioui.org)

Either way, you must rely on their support.

Moreover, Android does not support copy/paste images, which will be incomplete support for this package even if it is supported, see [Copy and Paste](https://developer.android.com/guide/topics/text/copy-paste).

Thus, closing.

**Comment by changkun** [comment]
OK, I changed my mind. I think it should at least support `gomobile`. The rest of the platforms should have their own support.

Reopen for mobile support.
